DROP TABLE FABRICANTES CASCADE CONSTRAINTS;

CREATE TABLE FABRICANTES(
  COD_FABRICANTE VARCHAR2(3) NOT NULL,
  NOMBRE VARCHAR2(15),
  PAIS VARCHAR2(15),
  
  CONSTRAINT fab_pk PRIMARY KEY (COD_FABRICANTE),
  CONSTRAINT fab_nombre_ch CHECK (NOMBRE =UPPER(NOMBRE)),
  CONSTRAINT fab_pais_ch CHECK (PAIS =UPPER(PAIS))
);

COMMIT;

DROP TABLE ARTICULOS CASCADE CONSTRAINTS;

CREATE TABLE ARTICULOS(
  ARTICULO VARCHAR2(20) NOT NULL,
  COD_FABRICANTE VARCHAR2(3) NOT NULL,
  PESO NUMBER(3) NOT NULL,
  CATEGORIA VARCHAR2(10) NOT NULL,
  PRECIO_VENTA NUMBER(4),
  PRECIO_COSTO NUMBER(4),
  EXISTECIAS NUMBER(5),
  
  CONSTRAINT art_pk PRIMARY KEY (ARTICULO,COD_FABRICANTE,PESO,CATEGORIA),
  CONSTRAINT art_fab_fk FOREIGN KEY (COD_FABRICANTE) REFERENCES FABRICANTES(COD_FABRICANTE),
  CONSTRAINT art_precioventa_ch CHECK(PRECIO_VENTA>0),
  CONSTRAINT art_preciocosto_ch CHECK(PRECIO_COSTO>0),
  CONSTRAINT art_peso_ch CHECK(PESO>0),
  CONSTRAINT art_categoria_ch CHECK (CATEGORIA IN ('Primera','Segunda','Tercera'))
);

COMMIT;

DROP TABLE TIENDAS CASCADE CONSTRAINTS;


CREATE TABLE TIENDAS(
  NIF VARCHAR2(10) NOT NULL,
  NOMBRE VARCHAR2(20),
  DIRECCION VARCHAR2(20),
  POBLACION VARCHAR2(20),
  PROVINCIA VARCHAR2(20),
  CODPOSTAL VARCHAR2(5),
  
  CONSTRAINT tien_pk PRIMARY KEY (NIF),
  CONSTRAINT tien_provincia_ch CHECK(PROVINCIA = upper(PROVINCIA))
);

COMMIT;


DROP TABLE PEDIDOS CASCADE CONSTRAINTS;

CREATE TABLE PEDIDOS(
  NIF VARCHAR2(10) NOT NULL,
  ARTICULO VARCHAR2(20) NOT NULL,
  COD_FABRICANTE VARCHAR2(3) NOT NULL,
  PESO NUMBER(3) NOT NULL,
  CATEGORIA VARCHAR2(10) NOT NULL,
  FECHA_PEDIDO DATE NOT NULL,
  UNIDADES_PEDIDAS NUMBER(4),
  
  CONSTRAINT ped_pk PRIMARY KEY (NIF, ARTICULO,COD_FABRICANTE, PESO, CATEGORIA,FECHA_PEDIDO),
  CONSTRAINT ped_fab_fk FOREIGN KEY(COD_FABRICANTE)REFERENCES FABRICANTES(COD_FABRICANTE),
  CONSTRAINT ped_unidadespedidas_ch CHECK (UNIDADES_PEDIDAS>0),
  CONSTRAINT ped_categoria_ch CHECK(CATEGORIA IN('Primera','Segunda','Tercera')),
  CONSTRAINT ped_art_fk FOREIGN KEY (ARTICULO,COD_FABRICANTE,PESO,CATEGORIA)REFERENCES ARTICULOS(ARTICULO,COD_FABRICANTE,PESO,CATEGORIA) ON DELETE CASCADE,
  CONSTRAINT ped_tien_fk FOREIGN KEY (NIF) REFERENCES TIENDAS(NIF)
);

COMMIT;

DROP TABLE VENTAS CASCADE CONSTRAINTS;

CREATE TABLE VENTAS(
  NIF VARCHAR2(10) NOT NULL,
  ARTICULO VARCHAR2(20) NOT NULL,
  COD_FABRICANTE VARCHAR2(3) NOT NULL,
  PESO NUMBER(3) NOT NULL,
  CATEGORIA VARCHAR2(10) NOT NULL,
  FECHA_VENTA DATE NOT NULL,
  UNIDADES_VENDIDAS NUMBER(4),
  
  CONSTRAINT vent_pk PRIMARY KEY(NIF, ARTICULO,COD_FABRICANTE, PESO, CATEGORIA,FECHA_VENTA),
  CONSTRAINT vent_fab_fk FOREIGN KEY (COD_FABRICANTE) REFERENCES FABRICANTES(COD_FABRICANTE),
  CONSTRAINT vent_unidadesvendidas_ch CHECK(UNIDADES_VENDIDAS>0),
  CONSTRAINT vent_categoria_ch CHECK(CATEGORIA IN('Primera', 'Segunda','Tercera')),
  CONSTRAINT vent_art_fk FOREIGN KEY (ARTICULO, COD_FABRICANTE, PESO,CATEGORIA) REFERENCES ARTICULOS(ARTICULO, COD_FABRICANTE, PESO,CATEGORIA),
  CONSTRAINT vent_tien_fk FOREIGN KEY (NIF) REFERENCES TIENDAS(NIF)
);

COMMIT;