DESC USER_TABLES
--COMPROBAR EXISTENCIA DE OBJETOS
SELECT table_name
FROM user_tables
WHERE INITCAP(table_name) IN('TIENDAS','Ventas','Pedidos','Articulos');

--COMPROBAR LAS COLUMNAS DE CADA TABLA
DESC TIENDAS
DESC ventas
DESC pedidos
DESC articulos
--COMPROBAR LAS RESTRICCIONES Y SUS COLUMNAS
SELECT CONSTRAINT_NAME,CONSTRAINT_TYPE,TABLE_NAME
FROM USER_CONSTRAINTS
WHERE INITCAP(table_name)IN('TIENDAS','Ventas','Pedidos','Articulos')
ORDER BY TABLE_NAME;

SELECT CONSTRAINT_NAME,CONSTRAINT_TYPE,TABLE_NAME
FROM USER_CONSTRAINTS
WHERE INITCAP(table_name)IN('TIENDAS','Ventas','Pedidos','Articulos')
ORDER BY TABLE_NAME;